gText_PkmnTransferredSomeonesPC:: @ 8273216
	.string "{STR_VAR_2} has been transferred\n"
	.string "to Box {STR_VAR_1}!$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} has been transferred\n"
	.string "to Box {STR_VAR_1}!$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "{STR_VAR_2} has been transferred\n"
	.string "to Box {STR_VAR_1}!$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "{STR_VAR_2} has been transferred\n"
	.string "to Box {STR_VAR_1}!$"

gText_NoMoreRoomForPokemon:: @ 827331C
	.string "There's no more room for Pokémon!\p"
	.string "The Pokémon Boxes are full and\n"
	.string "can't accept any more!$"

gText_NicknameThisPokemon:: @ 8273374
	.string "Give a nickname to the {STR_VAR_1}\n"
	.string "you caught?$"
